const timezones = [
  { id: "UTC-12", title: "UTC-12" },
  { id: "UTC-11", title: "UTC-11" },
  { id: "UTC-10", title: "UTC-10" },
  { id: "UTC-9", title: "UTC-9" },
  { id: "UTC-8", title: "UTC-8" },
  { id: "UTC-7", title: "UTC-7" },
  { id: "UTC-6", title: "UTC-6" },
  { id: "UTC-5", title: "UTC-5" },
  { id: "UTC-4", title: "UTC-4" },
  { id: "UTC-3", title: "UTC-3" },
  { id: "UTC-2", title: "UTC-2" },
  { id: "UTC-1", title: "UTC-1" },
  { id: "UTC+0", title: "UTC+0" },
  { id: "UTC+1", title: "UTC+1" },
  { id: "UTC+2", title: "UTC+2" },
  { id: "UTC+3", title: "UTC+3" },
  { id: "UTC+4", title: "UTC+4" },
  { id: "UTC+5", title: "UTC+5" },
  { id: "UTC+6", title: "UTC+6" },
  { id: "UTC+7", title: "UTC+7" },
  { id: "UTC+8", title: "UTC+8" },
  { id: "UTC+9", title: "UTC+9" },
  { id: "UTC+10", title: "UTC+10" },
  { id: "UTC+11", title: "UTC+11" },
  { id: "UTC+12", title: "UTC+12" },
];

export default timezones;
