import AuthenticatedLayout from "@/components/AuthenticatedLayout/AuthenticatedLayout";
import { getLoggedInUser } from "@/resources/auth/auth.service";
import { Metadata } from "next";
import { redirect } from "next/navigation";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthenticatedGroupLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getLoggedInUser().catch(() => null);
  console.log("AuthenticatedLayout Logged In User : ", user);
  if (!user) return redirect(`/auth/login`);
  if (1) return <div>Authenticated Layout</div>;
  return <AuthenticatedLayout>{children}</AuthenticatedLayout>;
}
