import React from "react";
import { Metadata } from "next";
import AuthenticatedLayout from "@/components/AuthenticatedLayout/AuthenticatedLayout";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <AuthenticatedLayout>{children}</AuthenticatedLayout>;
}
