export const plans = {
  organization: [
    {
      id: "1",
      name: "Small Business",
      description: "Perfect for startups and small teams",
      category: "Organization",
      price: "$49",
      freeForOneMonth: false,
      time: "Monthly",
      modules: [
        { id: "1", moduleName: "Task Manager", isActive: true },
        { id: "2", moduleName: "Calendar", isActive: true },
        { id: "3", moduleName: "Cloud Storage", isActive: true },
      ],
      features: [
        {
          id: "1",
          moduleId: "1",
          moduleName: "Task Manager",
          featureName: "Manage up to 5 Projects",
          properties: null,
          isActive: true,
        },
        {
          id: "2",
          moduleId: "1",
          moduleName: "Task Manager",
          featureName: "Task Management Tool with Time Tracker",
          properties: null,
          isActive: true,
        },
        {
          id: "3",
          moduleId: "2",
          moduleName: "Calendar",
          featureName: "Event Management",
          properties: null,
          isActive: true,
        },
        {
          id: "4",
          moduleId: "3",
          moduleName: "Cloud Storage",
          featureName: "100GB Shared Cloud Storage",
          properties: null,
          isActive: true,
        },
      ],
    },
    {
      id: "2",
      name: "Medium Business",
      description: "Perfect for growing businesses",
      category: "Organization",
      price: "$99",
      freeForOneMonth: true,
      time: "Monthly",
      modules: [
        { id: "1", moduleName: "Task Manager", isActive: true },
        { id: "2", moduleName: "Calendar", isActive: true },
        { id: "3", moduleName: "Cloud Storage", isActive: true },
        { id: "4", moduleName: "HRMS", isActive: true },
      ],
      features: [
        {
          id: "1",
          moduleId: "1",
          moduleName: "Task Manager",
          featureName: "Manage up to 10 Projects",
          properties: null,
          isActive: true,
        },
        {
          id: "2",
          moduleId: "1",
          moduleName: "Task Manager",
          featureName: "Task Management Tool with Time Tracker",
          properties: null,
          isActive: true,
        },
        {
          id: "3",
          moduleId: "2",
          moduleName: "Calendar",
          featureName: "Event Management",
          properties: null,
          isActive: true,
        },
        {
          id: "4",
          moduleId: "3",
          moduleName: "Cloud Storage",
          featureName: "250GB Shared Cloud Storage",
          properties: null,
          isActive: true,
        },
        {
          id: "5",
          moduleId: "4",
          moduleName: "HRMS",
          featureName: "Salary, Leave, Notice Management",
          properties: null,
          isActive: true,
        },
      ],
    },
    {
      id: "3",
      name: "Large Business",
      description: "Designed for enterprise & Large Scale Teams",
      category: "Organization",
      price: "$149",
      freeForOneMonth: true,
      time: "Monthly",
      modules: [
        { id: "1", moduleName: "Task Manager", isActive: true },
        { id: "2", moduleName: "Calendar", isActive: true },
        { id: "3", moduleName: "Cloud Storage", isActive: true },
        { id: "4", moduleName: "HRMS", isActive: true },
        { id: "5", moduleName: "CRMS", isActive: true },
      ],
      features: [
        {
          id: "1",
          moduleId: "1",
          moduleName: "Task Manager",
          featureName: "Manage up to 20 Projects",
          properties: null,
          isActive: true,
        },
        {
          id: "2",
          moduleId: "1",
          moduleName: "Task Manager",
          featureName: "Task Management Tool with Time Tracker",
          properties: null,
          isActive: true,
        },
        {
          id: "3",
          moduleId: "2",
          moduleName: "Calendar",
          featureName: "Event Management",
          properties: null,
          isActive: true,
        },
        {
          id: "4",
          moduleId: "3",
          moduleName: "Cloud Storage",
          featureName: "500GB Shared Cloud Storage",
          properties: null,
          isActive: true,
        },
        {
          id: "5",
          moduleId: "4",
          moduleName: "HRMS",
          featureName: "Employee Performance Tracking",
          properties: null,
          isActive: true,
        },
        {
          id: "6",
          moduleId: "5",
          moduleName: "CRMS",
          featureName: "CRMS Tool for Lead & Deals Management",
          properties: null,
          isActive: true,
        },
      ],
    },
  ],
  personal: [
    {
      id: "4",
      name: "Basic",
      description: "Perfect for personal use",
      category: "Personal",
      price: "0",
      freeForOneMonth: false,
      time: "Yearly",
      modules: [
        { id: "6", moduleName: "Mail", isActive: true },
        { id: "7", moduleName: "Communication Hub", isActive: true },
      ],
      features: [
        {
          id: "1",
          moduleId: "6",
          moduleName: "Mail",
          featureName: "Mail Module (Upto 2 emails)",
          properties: null,
          isActive: true,
        },
        {
          id: "2",
          moduleId: "7",
          moduleName: "Communication Hub",
          featureName: "Chatting only",
          properties: null,
          isActive: true,
        },
      ],
    },
    {
      id: "5",
      name: "Standard",
      description: "Perfect for personal use",
      category: "Personal",
      price: "$49",
      freeForOneMonth: false,
      time: "Yearly",
      modules: [
        { id: "6", moduleName: "Mail", isActive: true },
        { id: "8", moduleName: "Survey Tool", isActive: true },
      ],
      features: [
        {
          id: "1",
          moduleId: "6",
          moduleName: "Mail",
          featureName: "Mail Module (Unlimited)",
          properties: null,
          isActive: true,
        },
        {
          id: "2",
          moduleId: "8",
          moduleName: "Survey Tool",
          featureName: "Survey Tool with Assessment & Evaluation",
          properties: null,
          isActive: true,
        },
      ],
    },
    {
      id: "6",
      name: "Premium",
      description: "Perfect for personal use",
      category: "Personal",
      price: "$99",
      freeForOneMonth: true,
      time: "Yearly",
      modules: [
        { id: "6", moduleName: "Mail", isActive: true },
        { id: "9", moduleName: "AI Powered Intelligence", isActive: true },
      ],
      features: [
        {
          id: "1",
          moduleId: "6",
          moduleName: "Mail",
          featureName: "Mail Module with Enhanced Features",
          properties: null,
          isActive: true,
        },
        {
          id: "2",
          moduleId: "9",
          moduleName: "AI Powered Intelligence",
          featureName: "Smart Assistant Integration",
          properties: null,
          isActive: true,
        },
      ],
    },
  ],
};

export const categoryOptions = [
  { id: "1", name: "Organization" },
  { id: "2", name: "Personal" },
];
export const modules = [
  "Manage Organization",
  "Task Manager",
  "Analytics & Report",
  "Calendar",
  "Email",
  "Cloud Storage",
  "Notes",
  "HRMS",
  "CRMS",
  "Communication Hub",
  "Survey Tool",
];

export const features = [
  {
    moduleName: "Manage Organization",
    featureName: "Employee",
    properties: "Max Employee",
  },
  {
    moduleName: "Manage Organization",
    featureName: "Team",
    properties: "Max Team",
  },
  {
    moduleName: "Task Manager",
    featureName: "Time Tracker",
    properties: "",
  },
  {
    moduleName: "Task Manager",
    featureName: "Sprint Board",
    properties: "",
  },
  {
    moduleName: "Task Manager",
    featureName: "Projects",
    properties: "Max Projects",
  },
  {
    moduleName: "Analytics & Report",
    featureName: "Reports & Analytics",
    properties: [
      "General Report",
      "User Analytics",
      "Weekly Report",
      "Project Wise Report",
    ],
  },
  { moduleName: "Email", featureName: "Email", properties: "Max Email" },
  {
    moduleName: "Cloud Storage",
    featureName: "Cloud Storage",
    properties: "Max Storage",
  },
  { moduleName: "Calendar", featureName: "Calendar", properties: "" },
  {
    moduleName: "Calendar",
    featureName: "Event Management",
    properties: "",
  },
  { moduleName: "Notes", featureName: "Notes", properties: "" },
  {
    moduleName: "Notes",
    featureName: "AI Powered Intelligence",
    properties: "",
  },
  { moduleName: "HRMS", featureName: "Hirings", properties: "Maximum Posts" },
  { moduleName: "HRMS", featureName: "Payroll", properties: "" },
  {
    moduleName: "HRMS",
    featureName: "Employee Performance",
    properties: "",
  },
  { moduleName: "HRMS", featureName: "Leaves", properties: "" },
  { moduleName: "CRMS", featureName: "Lead Management", properties: "" },
  { moduleName: "CRMS", featureName: "Deal Management", properties: "" },
  {
    moduleName: "Communication Hub",
    featureName: "Channels",
    properties: "Maximum Channels",
  },
  {
    moduleName: "Communication Hub",
    featureName: "Calling",
    properties: "Maximum hours/day",
  },
  {
    moduleName: "Communication Hub",
    featureName: "Screen Sharing",
    properties: "",
  },
  {
    moduleName: "Survey Tool",
    featureName: "Surveys",
    properties: "Maximum surveys/day",
  },
  {
    moduleName: "Survey Tool",
    featureName: "Responses",
    properties: "Maximum responses/day",
  },
  {
    moduleName: "Survey Tool",
    featureName: "Assessment & Evaluation",
    properties: "Maximum assessments/day",
  },
];
